# Generated by Django 2.1.3 on 2019-06-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190610_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname',
            new_name='name',
        ),
    ]
