# Generated by Django 2.1.3 on 2019-06-10 03:22

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190610_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
