# Generated by Django 2.1.3 on 2019-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='ece', max_length=10),
        ),
    ]
