# Generated by Django 2.1.3 on 2019-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default='media/images/d1.jpg', upload_to='media/images'),
        ),
    ]
