# Generated by Django 2.1.2 on 2019-06-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20190610_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='video',
            field=models.FileField(default='media/images/d1.jpg', upload_to='videos/'),
        ),
    ]
